package Test;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.Collections;
import java.util.List;
import Test.MenuFrame;
import namelessgame.Database.DungeonDAO;
import namelessgame.Database.PlayerDAO;
import namelessgame.Gameplay.Dungeon;
import namelessgame.Gameplay.Game;
import namelessgame.Gameplay.Player;

/**
 *
 * @author Henrique Barcia Lang
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        Player player = Game.getPlayer();
        
        initComponents();
         
        playerName.setText(player.getName());
        playerLevel.setText(Integer.toString(player.getLevel()));
        
        playerExp.setStringPainted(true);
        playerExp.setValue((player.getExp() / player.getExpNeededToLevelUp()) * 100);
        playerExp.setToolTipText(player.getExp() + " / " + player.getExpNeededToLevelUp());
        // TODO set player avatar
        
        if(Game.getDungeons() == null)
        {
            List<Dungeon> dungeons = (new DungeonDAO()).loadDungeons();
            
            Collections.sort(dungeons);
            Game.setDungeons(dungeons);
        }
        
        if(Game.getShop().isEmpty())
            Game.fillShop();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerAvatar = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        playerName = new javax.swing.JLabel();
        playerLevel = new javax.swing.JLabel();
        playerExp = new javax.swing.JProgressBar();
        nameLabel = new javax.swing.JLabel();
        dungeonButton = new javax.swing.JButton();
        stashButton = new javax.swing.JButton();
        shopButton = new javax.swing.JButton();
        statusButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        playerAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/namelessgame/img/kirito.gif"))); // NOI18N
        getContentPane().add(playerAvatar);
        playerAvatar.setBounds(620, 60, 220, 330);

        levelLabel.setText("Lv.:");
        getContentPane().add(levelLabel);
        levelLabel.setBounds(590, 460, 50, 14);
        getContentPane().add(playerName);
        playerName.setBounds(630, 430, 110, 20);
        getContentPane().add(playerLevel);
        playerLevel.setBounds(630, 460, 50, 20);

        playerExp.setForeground(new java.awt.Color(204, 0, 255));
        getContentPane().add(playerExp);
        playerExp.setBounds(710, 450, 210, 30);

        nameLabel.setText("Name:");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(580, 430, 50, 14);

        dungeonButton.setText("Dungeon");
        getContentPane().add(dungeonButton);
        dungeonButton.setBounds(130, 100, 90, 23);

        stashButton.setText("Stash");
        stashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stashButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stashButton);
        stashButton.setBounds(290, 100, 80, 23);

        shopButton.setText("Shop");
        shopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shopButton);
        shopButton.setBounds(420, 100, 90, 23);

        statusButton.setText("Status");
        statusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButtonActionPerformed(evt);
            }
        });
        getContentPane().add(statusButton);
        statusButton.setBounds(130, 190, 90, 23);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(290, 190, 80, 23);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(870, 570, 55, 23);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/namelessgame/img/PATTERN-BRANCO.png"))); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 3480, 2160);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void shopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopButtonActionPerformed
        this.dispose();
        
        ShopFrame newShop = new ShopFrame();
        newShop.setVisible(true);
    }//GEN-LAST:event_shopButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        (new PlayerDAO()).savePlayer(Game.getPlayer());
    }//GEN-LAST:event_saveButtonActionPerformed

    private void statusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButtonActionPerformed
        this.dispose();
        
        StatusFrame newStatus = new StatusFrame();
        newStatus.setVisible(true);
    }//GEN-LAST:event_statusButtonActionPerformed

    private void stashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stashButtonActionPerformed
        this.dispose();
        
        StashFrame newStash = new StashFrame();
        newStash.setVisible(true);
    }//GEN-LAST:event_stashButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        
        Game.setPlayer(null);
        
        MenuFrame newMenu = new MenuFrame();
        newMenu.setVisible(true);
        
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton dungeonButton;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel playerAvatar;
    private javax.swing.JProgressBar playerExp;
    private javax.swing.JLabel playerLevel;
    private javax.swing.JLabel playerName;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton shopButton;
    private javax.swing.JButton stashButton;
    private javax.swing.JButton statusButton;
    // End of variables declaration//GEN-END:variables
}
