/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package namelessgame.View;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import namelessgame.Gameplay.Dungeon;
import namelessgame.Gameplay.Game;
import namelessgame.Gameplay.Player;

/**
 * Classe que cria o frame de seleção de dungeon.
 * @author Henrique Barcia Lang
 */
public class DungeonFrame extends javax.swing.JFrame {

    /**
     * Creates new form DungeonFrame
     */
    
    private Map<javax.swing.JButton, Dungeon> dungeonMap = new HashMap<>();
    private Player player = Game.getPlayer();
    
    public DungeonFrame() {
        initComponents();
        
        try
        {
            Dungeon dungeon1Data = Game.getDungeons().get(0);
            
            dungeonMap.put(dungeon1, dungeon1Data);
            dungeon1.setToolTipText("<html><h1>" +
                                    dungeon1Data.getName() + "</h1><br>" +
                                    dungeon1Data.getDescr() + "<br><br>" +
                                    "Minimum level: <font color = " + (player.getLevel() >= dungeon1Data.getMinLv() ? "\"green\"" : "\"red\"") + ">" + dungeon1Data.getMinLv() + "</font><br></html>");
            
            dungeon1.addActionListener(new java.awt.event.ActionListener() {           
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    DungeonActionPerformed(evt);
                }
            });
        }
        catch(Exception e)
        {
            System.out.println("Error when setting up dungeons... " + e.getMessage());
        }
    }
    
    /**
     * Ação realizada ao clicar em uma dungeon
     * @param evt 
     */
    private void DungeonActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JButton selectedButton = (javax.swing.JButton) evt.getSource();
        Dungeon myDungeon = dungeonMap.get(selectedButton);
        
        if(player.getLevel() < myDungeon.getMinLv())
        {
            Game.sendErrorMessage("You are not strong enough to explore this dungeon yet.");
            
            return;
        }
        
        int enterDungeon = JOptionPane.showConfirmDialog(this, "Are you sure you want to explore this dungeon?", "Explore dungeon", JOptionPane.YES_NO_OPTION);

        if(enterDungeon == 1)
            return;

        this.dispose();
        Game.startExploringDungeon(myDungeon);
        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        dungeon2 = new javax.swing.JButton();
        dungeon1 = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("    Dungeons");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/namelessgame/img/wooloo.png")).getImage());
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        infoLabel.setFont(new java.awt.Font("Yu Gothic Medium", 1, 48)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel.setText("Dungeons");
        getContentPane().add(infoLabel);
        infoLabel.setBounds(180, 10, 330, 110);

        dungeon2.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(dungeon2);
        dungeon2.setBounds(420, 310, 40, 30);

        dungeon1.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(dungeon1);
        dungeon1.setBounds(370, 500, 40, 30);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/namelessgame/img/map.png"))); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DungeonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DungeonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DungeonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DungeonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DungeonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton dungeon1;
    private javax.swing.JButton dungeon2;
    private javax.swing.JLabel infoLabel;
    // End of variables declaration//GEN-END:variables
}
