/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package namelessgame.View;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import namelessgame.Gameplay.Dungeon;
import namelessgame.Gameplay.Game;
import namelessgame.Gameplay.Player;

/**
 * Classe que cria o frame de seleção de dungeon.
 * @author Henrique Barcia Lang
 */
public class DungeonFrame extends javax.swing.JFrame {

    /**
     * Creates new form DungeonFrame
     */
    
    private Map<javax.swing.JButton, Dungeon> dungeonMap = new HashMap<>();
    private Player player = Game.getPlayer();
    
    public DungeonFrame() {
        initComponents();
        
        try
        {
            Dungeon dungeon1Data = Game.getDungeons().get(0);
            
            dungeonMap.put(dungeon1, dungeon1Data);
            dungeon1.setToolTipText("<html><h1>" +
                                    dungeon1Data.getName() + "</h1><br>" +
                                    dungeon1Data.getDescr() + "<br><br>" +
                                    "Minimum level: <font color = " + (player.getLevel() >= dungeon1Data.getMinLv() ? "\"green\"" : "\"red\"") + ">" + dungeon1Data.getMinLv() + "</font><br></html>");
            
            dungeon1.addActionListener(new java.awt.event.ActionListener() {           
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    DungeonActionPerformed(evt);
                }
            });
        }
        catch(Exception e)
        {
            System.out.println("Error when setting up dungeons... " + e.getMessage());
        }
    }
    
    /**
     * Ação realizada ao clicar em uma dungeon
     * @param evt 
     */
    private void DungeonActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JButton selectedButton = (javax.swing.JButton) evt.getSource();
        Dungeon myDungeon = dungeonMap.get(selectedButton);
        
        if(player.getLevel() < myDungeon.getMinLv())
        {
            Game.sendErrorMessage("You are not strong enough to explore this dungeon yet.");
            
            return;
        }
        
        int enterDungeon = JOptionPane.showConfirmDialog(this, "Are you sure you want to explore this dungeon?", "Explore dungeon", JOptionPane.YES_NO_OPTION);

        if(enterDungeon == 1)
            return;

        this.dispose();
        Game.startExploringDungeon(myDungeon);
        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        dungeon2 = new javax.swing.JButton();
        dungeon1 = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("    Dungeons");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/namelessgame/img/wooloo.png")).getImage());
        setPreferredSize(new java.awt.Dimension(827, 560));
        setResizable(false);
        getContentPane().setLayout(null);

        backButton.setFont(new java.awt.Font("OscineTrialW01-Regular", 0, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(710, 470, 100, 50);

        dungeon2.setBackground(new java.awt.Color(255, 0, 0));
        dungeon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dungeon2ActionPerformed(evt);
            }
        });
        getContentPane().add(dungeon2);
        dungeon2.setBounds(420, 220, 40, 30);

        dungeon1.setBackground(new java.awt.Color(255, 0, 0));
        dungeon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dungeon1ActionPerformed(evt);
            }
        });
        getContentPane().add(dungeon1);
        dungeon1.setBounds(370, 360, 40, 30);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/namelessgame/img/map.png"))); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 828, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dungeon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dungeon1ActionPerformed
        // TODO add your handling code here:
        Game.playSound("click1");
    }//GEN-LAST:event_dungeon1ActionPerformed

    private void dungeon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dungeon2ActionPerformed
        // TODO add your handling code here:
        Game.playSound("click1");
    }//GEN-LAST:event_dungeon2ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Game.playSound("click1");

        this.dispose();

        GameFrame gameBack = new GameFrame();
        gameBack.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DungeonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DungeonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DungeonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DungeonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DungeonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton dungeon1;
    private javax.swing.JButton dungeon2;
    // End of variables declaration//GEN-END:variables
}
