-- MySQL Script generated by MySQL Workbench
-- Mon Jun 10 02:33:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema namelessGame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema namelessGame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `namelessGame` DEFAULT CHARACTER SET utf8 ;
USE `namelessGame` ;

-- -----------------------------------------------------
-- Table `namelessGame`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `namelessGame`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `sex` VARCHAR(1) NOT NULL,
  `level` INT NULL DEFAULT 1,
  `exp` INT NULL DEFAULT 0,
  `gold` BIGINT NULL DEFAULT 0,
  `status_points` INT NULL DEFAULT 0,
  `str` INT NULL DEFAULT 5,
  `agi` INT NULL DEFAULT 5,
  `con` INT NULL DEFAULT 5,
  `head` INT NULL,
  `body` INT NULL,
  `weapon` INT NULL,
  `shield` INT NULL,
  `legs` INT NULL,
  `boots` INT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `namelessGame`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `namelessGame`.`inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`id`, `player_id`),
  INDEX `fk_inventory_player1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `namelessGame`.`player` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `namelessGame`.`stash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `namelessGame`.`stash` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`id`, `player_id`),
  INDEX `fk_stash_player1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_stash_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `namelessGame`.`player` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `namelessGame`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `namelessGame`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `str` INT NULL DEFAULT 0,
  `agi` INT NULL DEFAULT 0,
  `con` INT NULL DEFAULT 0,
  `heal` INT NULL DEFAULT 0,
  `slot` INT NULL DEFAULT 0,
  `min_lv` INT NULL DEFAULT 0,
  `name` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  `stackable` BIT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `namelessGame`.`dungeon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `namelessGame`.`dungeon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `descr` VARCHAR(45) NOT NULL,
  `min_lv` INT NULL DEFAULT 0,
  `background` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `namelessGame`.`monster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `namelessGame`.`monster` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `str` INT NULL DEFAULT 5,
  `agi` INT NULL DEFAULT 5,
  `con` INT NULL DEFAULT 5,
  `exp` INT NULL DEFAULT 0,
  `gold_min` INT NULL DEFAULT 0,
  `gold_max` INT NULL DEFAULT 0,
  `dungeon_id` INT NOT NULL,
  `round` INT NULL DEFAULT 1,
  `icon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `dungeon_id`),
  INDEX `fk_monster_dungeon1_idx` (`dungeon_id` ASC) VISIBLE,
  CONSTRAINT `fk_monster_dungeon1`
    FOREIGN KEY (`dungeon_id`)
    REFERENCES `namelessGame`.`dungeon` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `namelessGame`.`inventory_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `namelessGame`.`inventory_has_item` (
  `inventory_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `count` INT NULL DEFAULT 1,
  PRIMARY KEY (`inventory_id`, `item_id`),
  INDEX `fk_inventory_has_item_item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_inventory_has_item_inventory1_idx` (`inventory_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_has_item_inventory1`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `namelessGame`.`inventory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_has_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `namelessGame`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `namelessGame`.`stash_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `namelessGame`.`stash_has_item` (
  `stash_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `count` INT NULL DEFAULT 1,
  PRIMARY KEY (`stash_id`, `item_id`),
  INDEX `fk_stash_has_item_item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_stash_has_item_stash1_idx` (`stash_id` ASC) VISIBLE,
  CONSTRAINT `fk_stash_has_item_stash1`
    FOREIGN KEY (`stash_id`)
    REFERENCES `namelessGame`.`stash` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stash_has_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `namelessGame`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `namelessGame`.`monster_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `namelessGame`.`monster_has_item` (
  `monster_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `count_min` INT NULL DEFAULT 1,
  `chance` INT NULL DEFAULT 100,
  `count_max` INT NULL,
  PRIMARY KEY (`monster_id`, `item_id`),
  INDEX `fk_monster_has_item_item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_monster_has_item_monster1_idx` (`monster_id` ASC) VISIBLE,
  CONSTRAINT `fk_monster_has_item_monster1`
    FOREIGN KEY (`monster_id`)
    REFERENCES `namelessGame`.`monster` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monster_has_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `namelessGame`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
