/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package namelessgame.UI;

import javax.swing.JFrame;
import namelessgame.Gameplay.Item;
import namelessgame.Gameplay.ShopItem;

/**
 *
 * @author Henrique Barcia Lang
 */
public class ItemSliderFrame extends javax.swing.JFrame {

    /**
     * Creates new form ItemSliderFrame
     */
    
    private Item item;
    private int count = 1;
    private int countMax;    
    
    javax.swing.JFrame originalFrame;
    
    public void setItem(Item item)
    {
        this.item = item;
    }
    
    public void setCount(int count)
    {
        this.count = count;
    }
    
    public Item getItem()
    {
        return this.item;
    }
    
    public int getCount()
    {
        return this.count;
    }

    public int getCountMax() {
        return countMax;
    }

    public void setCountMax(int countMax) {
        this.countMax = countMax;
    }

    public JFrame getOriginalFrame() {
        return originalFrame;
    }

    public void setOriginalFrame(JFrame originalFrame) {
        this.originalFrame = originalFrame;
    }
    
    public ItemSliderFrame() {
        initComponents();
    }

    public ItemSliderFrame(javax.swing.JFrame originalFrame, Item item, int countMax) {
        initComponents();
        
        setOriginalFrame(originalFrame);
        setItem(item);
        setCountMax(countMax);
        
        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(item.getIcon())));
        amountLabel.setText(Integer.toString(1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sliderInfo = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        amountSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        sliderInfo.setText("Item amount");
        getContentPane().add(sliderInfo);
        sliderInfo.setBounds(80, 10, 80, 16);
        getContentPane().add(iconLabel);
        iconLabel.setBounds(10, 20, 50, 50);
        getContentPane().add(amountLabel);
        amountLabel.setBounds(30, 50, 20, 20);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(120, 50, 70, 20);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);
        okButton.setBounds(60, 50, 60, 20);

        amountSlider.setValue(1);
        amountSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                amountSliderStateChanged(evt);
            }
        });
        getContentPane().add(amountSlider);
        amountSlider.setBounds(60, 30, 120, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_amountSliderStateChanged
        int sliderValue = amountSlider.getValue();
        
        count = (sliderValue * countMax) / 100;
        amountLabel.setText(Integer.toString(count));
    }//GEN-LAST:event_amountSliderStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();

        // TODO if the originalFrame is closed, what happens?
        
        if(originalFrame instanceof ShopFrame)
        {
            if(!(item instanceof ShopItem))
                System.out.println("Error when downcasting Item to ShopItem on slider...");
            else
                ((ShopFrame) originalFrame).shopSliderAction((ShopItem) item, count);
        }
        else if(originalFrame instanceof StashFrame)
            ((StashFrame) originalFrame).stashSliderAction(item, count);
        else
            System.out.println("Slider used without being called by a configured frame...");
        
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemSliderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemSliderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemSliderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemSliderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemSliderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JSlider amountSlider;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel sliderInfo;
    // End of variables declaration//GEN-END:variables
}
