package namelessgame.Ui;

import java.util.List;
import java.util.ArrayList;
import namelessgame.Exception.GameIdNotFound;
import namelessgame.Game.Player;

/**
 *
 * @author sin
 */
public class loadGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form loadGameFrame
     */
    public loadGameFrame() {
        initComponents();
        
        String displayChars = "";
        
        for (Player player : newGameFrame.playerList) {
            displayChars += "Nickname: " + player.getName();
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name1 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        LoadGame1 = new javax.swing.JButton();
        LoadGame2 = new javax.swing.JButton();
        LoadGame3 = new javax.swing.JButton();
        LoadGame4 = new javax.swing.JButton();
        LoadGame5 = new javax.swing.JButton();
        LoadGame6 = new javax.swing.JButton();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        name1.setFont(new java.awt.Font("OscineW04-Light", 0, 24)); // NOI18N
        name1.setForeground(new java.awt.Color(51, 51, 51));
        name1.setText("Your games:");
        getContentPane().add(name1);
        name1.setBounds(120, 190, 180, 40);

        deleteButton.setFont(new java.awt.Font("OscineW04-Light", 0, 24)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(1030, 390, 100, 50);

        loadButton.setFont(new java.awt.Font("OscineW04-Light", 0, 24)); // NOI18N
        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loadButton);
        loadButton.setBounds(890, 390, 100, 50);

        id.setFont(new java.awt.Font("OscineW04-Light", 0, 24)); // NOI18N
        id.setForeground(new java.awt.Color(51, 51, 51));
        id.setText("Game id:");
        getContentPane().add(id);
        id.setBounds(890, 320, 100, 40);

        BackButton.setFont(new java.awt.Font("OscineW04-Light", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(1140, 670, 100, 30);

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idField);
        idField.setBounds(990, 320, 50, 40);

        LoadGame1.setFont(new java.awt.Font("OscineW04-Light", 0, 36)); // NOI18N
        LoadGame1.setText("Save 1");
        LoadGame1.setActionCommand("Game");
        LoadGame1.setMinimumSize(new java.awt.Dimension(300, 100));
        LoadGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGame1ActionPerformed(evt);
            }
        });
        getContentPane().add(LoadGame1);
        LoadGame1.setBounds(120, 240, 230, 80);

        LoadGame2.setFont(new java.awt.Font("OscineW04-Light", 0, 36)); // NOI18N
        LoadGame2.setText("Save 2");
        LoadGame2.setActionCommand("Game");
        LoadGame2.setMinimumSize(new java.awt.Dimension(300, 100));
        LoadGame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGame2ActionPerformed(evt);
            }
        });
        getContentPane().add(LoadGame2);
        LoadGame2.setBounds(400, 240, 230, 80);

        LoadGame3.setFont(new java.awt.Font("OscineW04-Light", 0, 36)); // NOI18N
        LoadGame3.setText("Save 3");
        LoadGame3.setActionCommand("Game");
        LoadGame3.setMinimumSize(new java.awt.Dimension(300, 100));
        LoadGame3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGame3ActionPerformed(evt);
            }
        });
        getContentPane().add(LoadGame3);
        LoadGame3.setBounds(120, 350, 230, 80);

        LoadGame4.setFont(new java.awt.Font("OscineW04-Light", 0, 36)); // NOI18N
        LoadGame4.setText("Save 4");
        LoadGame4.setActionCommand("Game");
        LoadGame4.setMinimumSize(new java.awt.Dimension(300, 100));
        LoadGame4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGame4ActionPerformed(evt);
            }
        });
        getContentPane().add(LoadGame4);
        LoadGame4.setBounds(400, 350, 230, 80);

        LoadGame5.setFont(new java.awt.Font("OscineW04-Light", 0, 36)); // NOI18N
        LoadGame5.setText("Save 5");
        LoadGame5.setActionCommand("Game");
        LoadGame5.setMinimumSize(new java.awt.Dimension(300, 100));
        LoadGame5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGame5ActionPerformed(evt);
            }
        });
        getContentPane().add(LoadGame5);
        LoadGame5.setBounds(120, 460, 230, 80);

        LoadGame6.setFont(new java.awt.Font("OscineW04-Light", 0, 36)); // NOI18N
        LoadGame6.setText("Save 6");
        LoadGame6.setActionCommand("Game");
        LoadGame6.setMinimumSize(new java.awt.Dimension(300, 100));
        LoadGame6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGame6ActionPerformed(evt);
            }
        });
        getContentPane().add(LoadGame6);
        LoadGame6.setBounds(400, 460, 230, 80);

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/namelessgame/img/PATTERN-BRANCO.png"))); // NOI18N
        Bg.setText("jLabel1");
        getContentPane().add(Bg);
        Bg.setBounds(0, 0, 1270, 750);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        int gameId;
        
        try
        {
            gameId = Integer.parseInt(idField.getText());
            
            // find game id (exception thrown in the method)
        }
        catch(NumberFormatException | GameIdNotFound e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Invalid game id.");
            
            return;
        }
        
        System.out.println("Loading into game...");
    }//GEN-LAST:event_loadButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        
        menuFrame menuBack = new menuFrame();
        menuBack.setVisible(true);
        menuBack.setSize(1280, 720);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void LoadGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGame1ActionPerformed
        this.dispose();

        newGameFrame newG = new newGameFrame();
        newG.setVisible(true);
        newG.setSize(1280, 720);
    }//GEN-LAST:event_LoadGame1ActionPerformed

    private void LoadGame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGame2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadGame2ActionPerformed

    private void LoadGame3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGame3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadGame3ActionPerformed

    private void LoadGame4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGame4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadGame4ActionPerformed

    private void LoadGame5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGame5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadGame5ActionPerformed

    private void LoadGame6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGame6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadGame6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loadGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loadGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loadGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loadGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loadGameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Bg;
    private javax.swing.JButton LoadGame1;
    private javax.swing.JButton LoadGame2;
    private javax.swing.JButton LoadGame3;
    private javax.swing.JButton LoadGame4;
    private javax.swing.JButton LoadGame5;
    private javax.swing.JButton LoadGame6;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel id;
    private javax.swing.JTextField idField;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel name1;
    // End of variables declaration//GEN-END:variables
}
